# Generated by Django 5.2.8 on 2025-12-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False)),
                ('family_group_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
