# Generated by Django 5.2.8 on 2025-12-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('family_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('family_name', models.CharField(max_length=100)),
            ],
        ),
    ]
