# Generated by Django 5.2.8 on 2025-12-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_familygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='ideal_gift',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='secret_friend_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
