# Generated by Django 5.2.8 on 2025-12-07 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_guest_ideal_gift_guest_secret_friend_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='family_group_id',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='secret_friend_id',
        ),
        migrations.AddField(
            model_name='guest',
            name='family_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='core.familygroup'),
        ),
        migrations.AddField(
            model_name='guest',
            name='secret_friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.guest'),
        ),
    ]
